version: "3"

volumes:
  new:

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=new
      - POSTGRES_USER=juice
      - POSTGRES_PASSWORD=21322132
    volumes:
      - new:/var/lib/postgresql/data
  web:
    build: .
    command: >
            bash -c "sleep 10 &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            echo \"from django.contrib.auth.models import User; User.objects.create_superuser('test', 'test@test.com', 'test')\" | python manage.py shell &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=new
      - POSTGRES_USER=juice
      - POSTGRES_PASSWORD=21322132
    depends_on:
      db:
        condition: service_started
